// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	PRICE_TRACKER: KVNamespace;
	NODE_VERSION: "20.0.0";
	DATABASE_URL: "xxxxxxxxxx";
}
