#:schema node_modules/wrangler/config-schema.json
name = "my-next-app"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[vars]
NODE_VERSION="20.0.0" # Define the Node version to avoid build errors.

[[kv_namespaces]]
binding = "MY_KV_NAMESPACE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[schedule]
crons = ["0 * * * *"] # Runs every hour