# Wrangler Configuration for the Price Tracker Cron Worker
name = "price-tracker-cron-worker"
main = "./src/index.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
NODE_VERSION = "20.0.0" # Define the Node.js version to avoid build errors.
API_URL = "https://price-tracker-1sh.pages.dev/api/cron"

[schedule]
crons = ["0 0 * * *"] # Every day at midnight UTC
